### ISSUE TITLE
Landing page mocks

### ISSUE THREAD

**Issue by matievisthekat** [Federation-of-Democratic-Seedlings/site#4]
# Landing Page
| Mobile | Desktop |
| --- | --- |
| ![Mobile](https://user-images.githubusercontent.com/45036977/139525643-a5a17394-e78b-4c50-b44e-e4efbec481b6.png) | ![Desktop](https://user-images.githubusercontent.com/45036977/139525641-02b9f002-f3a6-4a0f-8e2a-a5850e9204c7.png) |

**Comment by ErwinBeen** [comment]
Looking good. Like what you did with the logo!
