### ISSUE TITLE
Member page mocks

### ISSUE THREAD

**Issue by matievisthekat** [Federation-of-Democratic-Seedlings/site#5]
| Mobile | Desktop |
| --- | --- |
| ![Mobile](https://user-images.githubusercontent.com/45036977/139528196-449d1278-93a0-484e-9856-c9f884dd4ef0.png) | ![Desktop](https://user-images.githubusercontent.com/45036977/139527798-09e96744-7992-408d-a7af-c18bae582438.png) |

**Comment by ErwinBeen** [comment]
Honestly looking awesome! Is this manual work to change members or is there an plugin to get members from discord?

**Comment by matievisthekat** [comment]
We can get the members automatically, we'd have to add a discord bot to the server to access the members, but it shouldn't be too hard
